spring:
    application:
        name: contextiq
    datasource:
        url: jdbc:mysql://localhost:3306/context_iq
        username: sa
        password:  1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    config:
        import: optional:file:.env[.properties]
    data:
        redis:
            host: localhost
            port : 6379
server:
  port: 8080

gemini:
    api:
        key: ${GEMINI_API_KEY}
        url : https://generativelanguage.googleapis.com